version: '3.8'

services:
  dermatolog-ai-scan:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:

      - PROJECT_ID=${PROJECT_ID}
      - LOCATION=${LOCATION}
