version: '3.8'

services:
  medgemma-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HF_TOKEN=${HF_TOKEN}
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - PROJECT_ID=${PROJECT_ID}
      - HF_TOKEN=${HF_TOKEN}
